### ISSUE TITLE
TypeError on layout.ejs

### ISSUE THREAD

**Issue by gigavinyl** [probberechts/cactus-dark#8]
Every time I run "hexo server" with this theme installed and I try to render the page, I get this error:
```bash
Unhandled rejection TypeError: /home/gigavinyl/Projects/blog/themes/cactus-dark/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html<%= config.language ? " lang=" + config.language.substring(0, 2) : ""%>>
 >> 3| <%- partial('_partial/head') %>
    4| <body>
    5|     <% if (is_post()) { %>
    6|       <%- partial('_partial/header_post') %>

/home/gigavinyl/Projects/blog/themes/cactus-dark/layout/_partial/head.ejs:38
    36|     <% } %>
    37|     <% if (theme.rss) { %>
 >> 38|       <link rel="alternate" href="<%= url_for(theme.rss) %>" title="<%= config.title %>" type="application/atom+xml" />
    39|     <% } %>
    40|     <!-- jquery -->
    41|     <%- js('lib/jquery/jquery.min') %>

path.substring is not a function
    at Object.urlForHelper (/home/gigavinyl/Projects/blog/node_modules/hexo/lib/plugins/helper/url_for.js:9:31)
    at Object.wrapper [as url_for] (/home/gigavinyl/Projects/blog/node_modules/lodash/lodash.js:4994:19)
    at eval (eval at exports.compile (/home/gigavinyl/Projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:1735)
    at eval (eval at exports.compile (/home/gigavinyl/Projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:1991)
    at /home/gigavinyl/Projects/blog/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiledSync (/home/gigavinyl/Projects/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/gigavinyl/Projects/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/gigavinyl/Projects/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/gigavinyl/Projects/blog/node_modules/lodash/lodash.js:4994:19)
    at eval (eval at exports.compile (/home/gigavinyl/Projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:160)
    at eval (eval at exports.compile (/home/gigavinyl/Projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:796)
    at /home/gigavinyl/Projects/blog/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiled (/home/gigavinyl/Projects/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/gigavinyl/Projects/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/gigavinyl/Projects/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/gigavinyl/Projects/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/gigavinyl/Projects/blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/gigavinyl/Projects/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/gigavinyl/Projects/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/gigavinyl/Projects/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/gigavinyl/Projects/blog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/gigavinyl/Projects/blog/node_modules/bluebird/js/release/async.js:148:10)
```

**Comment by probberechts** [comment]
What value did you set `theme.rss` to? I noticed the README suggests that it should be an absolute path, however it will only work if you use a relative path because of the `url_for()`. I.e. `rss: http://your-site.com/atom.xml' won't work, but `rss: atom.xml` should work.

**Comment by gigavinyl** [comment]
@probberechts Yep, that was the issue. Changing the value of `theme.rss` to `rss: atom.xml` did the trick. Thanks :smile:

**Comment by Kemuda** [comment]
the solve above. 
My particular error is:

`Unhandled rejection TypeError: /Users/amber/Documents/Blog/themes/cactus/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html<%= config.language ? " lang=" + config.language.substring(0, 2) : ""%>>
 >> 3| <%- partial('_partial/head') %>
    4| <body class="max-width mx-auto px3 <%- theme.direction -%>">
    5|     <% if (is_post()) { %>
    6|       <%- partial('_partial/post/actions_desktop') %>

/Users/amber/Documents/Blog/themes/cactus/layout/_partial/head.ejs:66
    64|     <% } %>
    65| 	
 >> 66| 	<% if (theme.mathjax.enabled) {%>
    67| 		<script type="text/x-mathjax-config">
    68| 		  MathJax.Hub.Config({
    69| 			tex2jax: {

Cannot read property 'enabled' of undefined
    at eval (/Users/amber/Documents/Blog/themes/cactus/layout/_partial/head.ejs:165:26)
    at head (/Users/amber/Documents/Blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/amber/Documents/Blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/amber/Documents/Blog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/amber/Documents/Blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/Users/amber/Documents/Blog/themes/cactus/layout/layout.ejs:15:17)
    at layout (/Users/amber/Documents/Blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/amber/Documents/Blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/amber/Documents/Blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/amber/Documents/Blog/node_modules/hexo/lib/theme/view.js:51:25
    at tryCatcher (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/amber/Documents/Blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)`
